/*DROP DATABASE MUTUALFUNDDB;*/
CREATE DATABASE IF NOT EXISTS MUTUALFUNDDB; 
USE MUTUALFUNDDB;

CREATE TABLE IF NOT EXISTS MUTUAL_FUND_HOUSE (
	MF_HOUSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    MF_HOUSE_NAME VARCHAR(255),
    CONSTRAINT MUTUAL_FUND_HOUSE_CONST UNIQUE(MF_HOUSE_NAME)
);

CREATE TABLE IF NOT EXISTS MUTUAL_FUND_SCHEME_TYPE (
  MF_SCHEME_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
  MF_SCHEME_TYPE VARCHAR(255),
  CONSTRAINT  MUTUAL_FUND_SCHEME_TYPE_CONST UNIQUE(MF_SCHEME_TYPE)
);

CREATE TABLE IF NOT EXISTS MUTUAL_FUND_SCHEME (
  MF_SCHEME_ID INT AUTO_INCREMENT PRIMARY KEY,
  MF_SCHEME_NAME VARCHAR(255),
  MISSION_STATEMENT TEXT,
  MF_HOUSE_ID INT,
  MF_SCHEME_TYPE_ID INT,
  FOREIGN KEY (MF_HOUSE_ID) REFERENCES MUTUAL_FUND_HOUSE(MF_HOUSE_ID),
  FOREIGN KEY (MF_SCHEME_TYPE_ID) REFERENCES MUTUAL_FUND_SCHEME_TYPE(MF_SCHEME_TYPE_ID),
  CONSTRAINT MUTUAL_FUND_SCHEME_CONST UNIQUE(MF_HOUSE_ID,MF_SCHEME_NAME)
);

CREATE TABLE IF NOT EXISTS INDUSTRY(
  INDUSTRY_ID INT AUTO_INCREMENT PRIMARY KEY,
  INDUSTRY_NAME VARCHAR(255),
  CONSTRAINT INDUSTRY_CONST UNIQUE(INDUSTRY_NAME)
);

CREATE TABLE IF NOT EXISTS EQUITY_INFO(
  EQU_ID INT AUTO_INCREMENT PRIMARY KEY,
  EQU_NAME VARCHAR(255),
  EQU_SYMBOL VARCHAR(255),
  INDUSTRY_ID INT,
  FOREIGN KEY (INDUSTRY_ID) REFERENCES INDUSTRY(INDUSTRY_ID),
  CONSTRAINT EQUITY_INFO_CONST UNIQUE(EQU_NAME,EQU_SYMBOL)
);

CREATE TABLE IF NOT EXISTS ISIN_INFO (
  ISIN_ID VARCHAR(255) PRIMARY KEY,
  EQU_ID INT,
  FOREIGN KEY (EQU_ID) REFERENCES EQUITY_INFO(EQU_ID),
  CONSTRAINT ISIN_INFO_CONST UNIQUE(ISIN_ID,EQU_ID)
);

CREATE TABLE IF NOT EXISTS MF_EQUITY_MAP (
  MF_EQUITY_MAP_ID INT PRIMARY KEY,
  MF_SCHEME_ID INT,
  EQU_ID INT,
  PORTFOLIO_MONTH VARCHAR(255),
  FOREIGN KEY (EQU_ID) REFERENCES EQUITY_INFO(EQU_ID),
  FOREIGN KEY (MF_SCHEME_ID) REFERENCES MUTUAL_FUND_SCHEME(MF_SCHEME_ID)
);

CREATE TABLE IF NOT EXISTS EQUITY_QUANTITY (
  EQU_QUANTITY_ID INT PRIMARY KEY,
  EQU_QUANTITY DOUBLE,
  FOREIGN KEY (EQU_QUANTITY_ID) REFERENCES MF_EQUITY_MAP(MF_EQUITY_MAP_ID)
);

CREATE TABLE IF NOT EXISTS EQUITY_MARKET_VALUE (
  EQU_MARKEY_VALUE_ID INT PRIMARY KEY,
  EQU_MARKET_VALUE DOUBLE,
  FOREIGN KEY (EQU_MARKEY_VALUE_ID) REFERENCES MF_EQUITY_MAP(MF_EQUITY_MAP_ID)
);

CREATE TABLE IF NOT EXISTS EQUITY_PERCENT_OFAUM (
  EQU_PERCENT_OFAUM_ID INT PRIMARY KEY,
  EQU_PERCENT_OFAUM FLOAT,
  FOREIGN KEY (EQU_PERCENT_OFAUM_ID) REFERENCES MF_EQUITY_MAP(MF_EQUITY_MAP_ID)
);
